import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [

   {
    _id: uuid(),
    title: "Kinetic Blazer Slate grey",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1602531083-mos-flats-men-s-kinetic-blazer-slate-grey_fangod.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 4.5,
    arrivedNewly: true,
    sale: false
  },
     {
    _id: uuid(),
    title: "Velocity Dark Navy",
    price: "2000",
    discountedPrice:"1900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1602680985-mos-flats-men-s-velocity-blazer-dark-navy_jxyoaf.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 4.5,
    arrivedNewly: false,
    sale: false
  },
     {
    _id: uuid(),
    title: "Velocity Marino Black",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1623782770-mos-flats-men-s-velocity-merino-blazer-black-wool_pyfkhl.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 2.7,
    arrivedNewly: true,
    sale: true
  },
     {
    _id: uuid(),
    title: "Velocity graphite dark",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1602307944-mos-flats-men-s-velocity-blazer-charcoal_af5iww.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 2.5,
    arrivedNewly: true,
    sale: false
  },
         {
    _id: uuid(),
    title: "Velocity Black",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: false,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1602531121-mos-flats-men-s-velocity-blazer-black_vr8gdr.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 1.9,
    arrivedNewly: true,
    sale: false
  },
                {
    _id: uuid(),
    title: "Velocity Blue",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087557/Assets%20For%20Ecom/Jackets/1602300390-mos-flats-men-s-velocity-blazer-blue-houndstooth_f3eh5j.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 1.7,
    arrivedNewly: true,
    sale: true
  },
           {
    _id: uuid(),
    title: "Kinetic dot air navy heather",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602105143-mos-flats-men-s-velocity-blazer-indigo-heather_vrrqyn.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 4.0,
    arrivedNewly: true,
    sale: false
  },
    {
    _id: uuid(),
    title: "Velocity indigo",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602105143-mos-flats-men-s-velocity-blazer-indigo-heather_vrrqyn.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 4.5,
    arrivedNewly: false,
    sale: false
  },
          {
    _id: uuid(),
    title: "Kinetic Indigo",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602104992-mos-flats-men-s-kinetic-blazer-indigo-heather_gwad6m.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 3.2,
    arrivedNewly: false,
    sale: false
  },
           {
    _id: uuid(),
    title: "Kinetic Navy",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602105000-mos-flats-men-s-kinetic-blazer-navy_eyqise.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 3.4,
    arrivedNewly: true,
    sale: false
  },
         {
    _id: uuid(),
    title: "Kinetic Charcoal",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: false,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602104974-mos-flats-men-s-kinetic-blazer-charcoal-heather_mdbyff.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 4.7,
    arrivedNewly: false,
    sale: false
  },
                {
    _id: uuid(),
    title: "Kinetic Black",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Jacket",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649087556/Assets%20For%20Ecom/Jackets/1602104965-mos-flats-men-s-kinetic-blazer-black_wmzx0w.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 3.5,
    arrivedNewly: true,
    sale: false
  },
                  {
    _id: uuid(),
    title: "Velocity Pant Black",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621416/Assets%20For%20Ecom/Trousers/1611698189-mos-flats-men-s-velocity-pant-graphite_1_dr3sdd.webp",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 4.0,
    arrivedNewly: false,
    sale: false
  },
           {
    _id: uuid(),
    title: "Velocity Pant Calcite heather",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621416/Assets%20For%20Ecom/Trousers/1611698014-mos-flats-men-s-velocity-pant-calcite-heather_1_g1kx1n.webp",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 5,
    arrivedNewly: true,
    sale: false
  },
                  {
    _id: uuid(),
    title: "Velocity Pant Graphite",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621416/Assets%20For%20Ecom/Trousers/1611698189-mos-flats-men-s-velocity-pant-graphite_tafe2v.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 3.6,
    arrivedNewly: false,
    sale: false
  },
    {
    _id: uuid(),
    title: "Velocity Azurite heather",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: false,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621415/Assets%20For%20Ecom/Trousers/1608058643-mos-mens-velocity-suit-pant-azurite-heather-1_cwzpb2.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 2.7,
    arrivedNewly: true,
    sale: false
  },
     {
    _id: uuid(),
    title: "Velocity Charcoal",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621415/Assets%20For%20Ecom/Trousers/1574959815-mos-mens-velocity-suit-pant-charcoal-4_1_flcuxb.webp",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 2.9,
    arrivedNewly: false,
    sale: true
  },
     {
    _id: uuid(),
    title: "Kinetic Adaptive black",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621415/Assets%20For%20Ecom/Trousers/1604070815-mos-mens-kinetic-adaptive-pant-black-1_jy0tpw.jpg",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 2.5,
    arrivedNewly: true,
    sale: false
  },
     {
    _id: uuid(),
    title: "Velocity Azurite heather",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621415/Assets%20For%20Ecom/Trousers/1603821205-mos-mens-kinetic-adaptive-pant-navy-1_dsbgdg.jpg",
    brandName: "Velocity",
    offer: 100,
    quantity: 0,
    rating: 3.0,
    arrivedNewly: false,
    sale: false
  },
    {
    _id: uuid(),
    title: "Kinetic Adaptive Navy",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Trouser",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1648621415/Assets%20For%20Ecom/Trousers/1603821205-mos-mens-kinetic-adaptive-pant-navy-1_1_hshha6.webp",
    brandName: "Kinetic",
    offer: 100,
    quantity: 0,
    rating: 3.2,
    arrivedNewly: true,
    sale: true
  },
   {
    _id: uuid(),
    title: "Valencia Suit",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: false,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101463/Assets%20For%20Ecom/Suits/eph_the-valencia-suit_feature_myrqwy.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 3.7,
    arrivedNewly: false,
    sale: true
  },
     {
    _id: uuid(),
    title: "True Blue Suit",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101462/Assets%20For%20Ecom/Suits/eph_the-true-blue-suit_feature_i1kupx.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 3.4,
    arrivedNewly: true,
    sale: false
  },
      {
    _id: uuid(),
    title: "The SmithSonian",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101462/Assets%20For%20Ecom/Suits/eph_the-smithsonian-suit_feature_nd570q.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 3.6,
    arrivedNewly: false,
    sale: false
  },
   {
    _id: uuid(),
    title: "The Sage Silk Herringbone",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101461/Assets%20For%20Ecom/Suits/eph_the-sage-silk-herringbone-suit_feature_esnedo.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 3.5,
    arrivedNewly: true,
    sale: false
  },
   {
    _id: uuid(),
    title: "Polo Widowpane",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101459/Assets%20For%20Ecom/Suits/eph_the-Polo-Windowpane_Feature_sofvkr.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 3.9,
    arrivedNewly: false,
    sale: true
  },
    {
    _id: uuid(),
    title: "The Mackenzie",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101462/Assets%20For%20Ecom/Suits/eph_the-true-blue-suit_feature_i1kupx.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 4.3,
    arrivedNewly: false,
    sale: false
  },
     {
    _id: uuid(),
    title: "The granite grey",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101453/Assets%20For%20Ecom/Suits/eph_the-granite-grey-suit_feature_lacdtk.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 4,
    arrivedNewly: false,
    sale: false
  },
      {
    _id: uuid(),
    title: "The Charcoal Microcheck",
    price: "6000",
    discountedPrice:"5900",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: false,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101450/Assets%20For%20Ecom/Suits/eph_the-charcoal-microcheck_feature_u8rcb7.jpg",
    brandName: "Suit",
    offer: 100,
    quantity: 0,
    rating: 1.9,
    arrivedNewly: true,
    sale: false
  },
       {
    _id: uuid(),
    title: "The Bridgeport Blue",
    price: "90000",
    discountedPrice:"88000",
    categoryName:"Suit",
    inStock: false,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101446/Assets%20For%20Ecom/Suits/eph_the-bridgeport-blue-suit_feature_drp0q8.jpg",
    brandName: "Suit",
    offer: 2000,
    quantity: 0,
    rating: 4,
    arrivedNewly: false,
    sale: false
  },
        {
    _id: uuid(),
    title: "Teal Nano two piece",
    price: "25000",
    discountedPrice:"24000",
    categoryName:"Suit",
    inStock: true,
    fastDelivery: true,
    imageURL: "https://res.cloudinary.com/doo5jbomi/image/upload/v1649101445/Assets%20For%20Ecom/Suits/Eph_teal-nano-two-piece_feature_o9qwja.jpg",
    brandName: "Suit",
    offer: 1000,
    quantity: 0,
    rating: 4.5,
    arrivedNewly: false,
    sale: true
  },
];
