export const ACTION_TYPE = {
    CATEGORIES: "CATEGORIES",
    PRODUCTS: "PRODUCTS",
    PRICE_RANGE: "PRICE_RANGE",
    RATING: "RATING",
    SORT_BY: "SORT_BY",
    FAST_DELIVERY: "FAST_DELIVERY",
    STOCK: "STOCK",
    STATUS: "STATUS",
    HIGH_TO_LOW: "HIGH_TO_LOW",
    LOW_TO_HIGH: "LOW_TO_HIGH",
    CLEAR: "CLEAR",
}
